travis:
  secure:
    BINSTAR_TOKEN: IsU16cf1QW3ue5KoU0Hb8btpLHS477P8mLlDq1q7+zKKtgwVqhGfy/zR+7vk7Y2R791lpmHVp7LK/Kl//HRlYuIrEZrd08iDIe/X7f8tKtmSIIuy7w2tj+KXXb0URoLQxBC32V4GNSMmfND/xLpuon4C6L6GZ7PFisWa0t1rQbXXnBhpYyJmQqoPuwWRjixlIp2mFHNbYBeYFDdxxIXbBT+/TlhI/pycwJkRPYoJKi9gDmBbqJ+b1qo7BqC9VeL7FO2MEtn7e57wv90H9WqUsCZwSkuDDPF4usnvcTPNolthrsr6EBn/hSuM1sYWYIqBDpWxafLO3r4FfGH/J+6/6xq3po8Jz/s7XgDGCzAfSxf1+sn4zK2kbC1LR3Pr5bHbsNRzZADKxYQZz07aJzg0dJDwW6Uiro6KJxI1nmRP+iXqN2bRki+JLl6hxYWP3Xf75ia99LokoppNd5GDAIqzXyAy3/8o10+sgJV693mee+GfiFitYHDrymizTYSuSJKEX/DBh4wGtBUQqBSqzcJMg+FFc6CXQ3rxymclv8kjyJ06ApZC0zQSCsKMxj5wN4JMcJL2xNp5rfH3Q4t6gDbB87kP8xmLagp3QtNr2pfAJIjLuiXeClYqoGoDAgJkJW/UJB0/DxfZFMiau2pgIellxN258hSo1kxrChKBrHPu4vE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
